helloworld/urls.py
# coding: utf-8
"""helloworld URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from . import view
from testModel import views
from book.tv import qq
from book import views as book_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello$', view.hello),
    url(r'^qq/$', qq.show ),
    #url(r'^display/$', book_views.display_meta ),
    url(r'^display/$', book_views.display_meta_by_tpl),
    url(r'^book/author_form/$', book_views.author_form),
    url(r"abcd/(\d+)/(\d+)/$", view.test_url, name="abc"),
    url(r"home/$", view.home, name="home"),
    url(r"^jobtask/", include("jobtask.urls", namespace="jobtask")),   # 使用include
]

jobtask/backup/20170913/urls.py
from django.conf.urls import url


from jobtask import views as jobtask_views

app_name = "jobtask"  # namespace
urlpatterns = [
    #url(r"taskdef/add$", jobtask_views.taskadd, name="taskdef-add"),
    url(r"taskdef/add$", jobtask_views.taskdef_add_view.as_view(), name="taskdef-add"),
    url(r'^taskdef/(?P<pk>\d+)$', jobtask_views.taskdef_detail_view.as_view(), name='taskdef-detail'),
    url(r'^taskdef/action$', jobtask_views.taskdef_action_view.as_view(), name='taskdef-action'),
    url(r"taskdef/list$", jobtask_views.taskdef_list_view.as_view(), name="taskdef-list"),
    # ajax
    url(r"taskdef/status$", jobtask_views.TaskStatus, name="taskdef-status"),
    url(r"taskdef/type$", jobtask_views.TaskType, name="taskdef-type"),
    url(r"taskdef/perm$", jobtask_views.TaskPerm, name="taskdef-perm"),
    url(r"taskdef/filetype$", jobtask_views.FileType, name="taskdef-filetype"),
]

jobtask/urls.py
#coding=utf-8
"""helloworld URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url


import views

app_name = "jobtask"  # namespace
urlpatterns = [
    ## TaskDef
    #url(r"taskdef/add$", jobtask_views.taskadd, name="taskdef-add"),
    url(r"taskdef/add$", views.TaskDef.AddView.as_view(), name="taskdef-add"),
    url(r'^taskdef/(?P<pk>\d+)$', views.TaskDef.DetailView.as_view(), name='taskdef-detail'), #old
    url(r"^taskdef/list$", views.TaskDef.ListView.as_view(), name="taskdef-list"),
    # ajax
    url(r"^taskdef/status$", views.Ajax.TaskStatus, name="taskdef-status"),
    url(r"^taskdef/type$", views.Ajax.TaskType, name="taskdef-type"),
    url(r"^taskdef/perm$", views.Ajax.TaskPerm, name="taskdef-perm"),
    url(r"^taskdef/filetype$", views.Ajax.FileType, name="taskdef-filetype"),
    url(r"^taskdef/fileloc$", views.Ajax.FileLocation, name="taskdef-filelocation"),
    url(r"^iplist$", views.Ajax.IpList, name="comm-iplist"),
    ## CommTaskDef
    url(r"^comm_taskdef/new$", views.CommTaskDef.AddView.as_view(), name="comm_taskdef-new"),
    url(r"^comm_taskdef/list$", views.CommTaskDef.ListView.as_view(), name="comm_taskdef-list"),
    url(r"^comm_taskdef/(?P<pk>\d+)$", views.CommTaskDef.DetailView.as_view(), name="comm_taskdef-detail"),
    url(r"^comm_taskdef/modal/(?P<pk>\d+)$", views.CommTaskDef.DetailViewForModal.as_view(), name="comm_taskdef-detail_for_modal"),
    ## CommJobDef
    url(r"^comm_jobdef/new$", views.CommJobDef.AddView.as_view(), name="comm_jobdef-new"),
    url(r"^comm_jobdef/list$", views.CommJobDef.ListView.as_view(), name="comm_jobdef-list"),
    url(r"^comm_jobdef/(?P<pk>\d+)$", views.CommJobDef.DetailView.as_view(), name="comm_jobdef-detail"),
    url(r"^comm_jobdef/modal/(?P<pk>\d+)$", views.CommJobDef.DetailViewForModal.as_view(), name="comm_jobdef-detail_for_modal"),

    ## Job
    url(r"^job/list$", views.Job.ListView.as_view(), name="job-list"),
    url(r"^job/(?P<pk>\d+)/(?P<jobid>\d+)$", views.Job.DetailView.as_view(), name="job-detail"),
    #url(r"^job/(?P<pk>\d+)$", views.Job.DetailView.as_view(), name="job-detail"),
    url(r"^job/run/(\d+)$", views.Job.RunJob.as_view(), name="job-new"),
    ## JobTask
    url(r"^jobtask/list$", views.JobTask.ListView.as_view(), name="jobtask-list"),
    url(r"^jobtask/(?P<pk>\d+)/(?P<jobid>\d+)/(?P<job_order_id>\d+)$", views.JobTask.DetailView.as_view(), name="jobtask-detail"),
    ## JobSubTask
    url(r"^jobsubtask/list$", views.JobSubTask.ListView.as_view(), name="jobsubtask-list"),
    url(r"^jobsubtask/(?P<pk>\d+)/(?P<taskid>\d+)$", views.JobSubTask.DetailView.as_view(), name="jobsubtask-detail"),
    ## Task
    url(r"^task/list$", views.Task.ListView.as_view(), name="task-list"),
    url(r"^task/(?P<pk>\d+)/(?P<taskid>\d+)$", views.Task.DetailView.as_view(), name="task-detail"),
    url(r"^task/commtask/run/(\d+)$", views.Task.Run.as_view(), name="comm-task-run"),
    url(r"^task/run/(\d+)$", views.Task.RunTask.as_view(), name="task-run"),
    ## SubTask
    url(r"^subtask/list$", views.SubTask.ListView.as_view(), name="subtask-list"),
    url(r"^subtask/(?P<pk>\d+)/(?P<taskid>\d+)$", views.SubTask.DetailView.as_view(), name="subtask-detail"),
]

## 用户
urlpatterns += [
    ## TaskDef
    url(r"task/def$", views.TaskDef.AddView.as_view(), name="create-my-taskdef"),
    url(r"^task/def/my$", views.TaskDef.ListView.as_view(), {"user-open": True}, name="my-taskdef-list"),
    #url(r'^task/def/my/(?P<pk>\d+)$', views.TaskDef.DetailView.as_view(), name='my-taskdef-detail'), #old
    url(r"^comm_taskdef/list/my$", views.CommTaskDef.ListView.as_view(), {"user-open": True}, name="my-comm-taskdef-list"),
    url(r"^comm_taskdef/listtask/my$", views.CommTaskDef.ListTask.as_view(), {"user-open": True}, name="my-comm-taskdef-list-task"),
    url(r"^comm_jobdef/list/my$", views.CommJobDef.ListView.as_view(), {"user-open": True}, name="my-comm-jobdef-list"),
    url(r"^job/list/my$", views.Job.ListView.as_view(), {"user-open": True}, name="my-job-list"),
    url(r"^jobtask/list/my$", views.JobTask.ListView.as_view(), {"user-open": True}, name="my-jobtask-list"),
    url(r"^task/list/my$", views.Task.ListView.as_view(), {"user-open": True}, name="my-task-list"),
]

jobtask/backup/20170913/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

## 资源控制配置表
class Res_Control_Conf(models.Model):
    mem = models.IntegerField(verbose_name="内存要求(M)")
    mem_percent = models.IntegerField(verbose_name="内存要求(%)")
    sys_load_1 = models.FloatField(verbose_name="系统负载要求(1m)")
    sys_load_5 = models.FloatField(verbose_name="系统负载要求(5m)")
    sys_load_15 = models.FloatField(verbose_name="系统负载要求(15m)")

## 任务定义表
class Task_Def(models.Model):
    file = models.FileField(upload_to="upload/%Y/%m/%d", null=True, verbose_name="文件路径")  #文件
    #filepath = models.CharField(max_length=255, verbose_name="文件路径")  #文件
    file_type = models.SmallIntegerField(verbose_name="文件类型")  # 脚本或脚本包
    main_script_name = models.CharField(max_length=64, verbose_name="主脚本名")
    #path = models.CharField(max_length=255, verbose_name="文件路径")
    params = models.TextField(verbose_name="参数")
    executor = models.CharField(max_length=16, verbose_name="解析器")
    func = models.TextField(verbose_name="功能说明")
    task_status = models.SmallIntegerField(verbose_name="任务状态")
    task_type = models.SmallIntegerField(verbose_name="任务类型")
    task_perm_status = models.SmallIntegerField(verbose_name="任务权限状态")
    res_ctl_conf =  models.ForeignKey(Res_Control_Conf, verbose_name="主机资源控制", null=True) 
    create_user = models.CharField(max_length=64, verbose_name="创建用户")
    create_dt = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)
    update_dt = models.DateTimeField(blank=True, null=True, verbose_name="更新时间", auto_now=True)
    note = models.TextField(verbose_name="备注")

## 常规任务表，已配置好
class Comm_Task_Def(models.Model):
    task = models.ForeignKey(Task_Def, verbose_name="任务定义")
    func = models.TextField(verbose_name="功能说明")
    exe_user = models.CharField(max_length=64, verbose_name="执行用户") # 在远程主机上执行脚本或任务，主机上的用户
    params = models.TextField(verbose_name="参数")
    create_user = models.CharField(max_length=64, verbose_name="创建用户")
    create_dt = models.DateTimeField(verbose_name="创建时间")
    update_dt = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    iphosts = models.TextField(verbose_name="IP或主机名") # 在远程主机上执行脚本或任务，主机上的用户
    timeout = models.IntegerField(verbose_name="超时时间")
    note = models.TextField(verbose_name="备注") # 在远程主机上执行脚本或任务，主机上的用户
    
## 常规作业表，已配置好
class Comm_Job_Def(models.Model):
    func = models.TextField(verbose_name="功能说明")
    comm_tasks = models.ManyToManyField(Comm_Task_Def, verbose_name="任务列表")
    job_status = models.SmallIntegerField(verbose_name="任务状态")  # 0：停用；1：启用
    job_type = models.SmallIntegerField(verbose_name="任务类型")  # 0：系统作业；2业务作业
    job_perm_status = models.SmallIntegerField(verbose_name="任务权限状态")  # 0：独有不公开  1：所有人可读
    create_user = models.CharField(max_length=64, verbose_name="创建用户")
    create_dt = models.DateTimeField(verbose_name="创建时间")
    update_dt = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    note = models.TextField(verbose_name="备注")
    
# 创建作业
# 创建任务

# 任务表
class Job(models.Model):
    jobid = models.CharField(max_length=64, verbose_name="作业ID") 
    create_dt = models.DateTimeField(verbose_name="创建时间")
    update_dt = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    job_status =  models.SmallIntegerField(verbose_name="作业状态")   # 0：失败  1：成功  2：等待  3：执行中
    
    class Meta:
        indexes = [
            models.Index(fields=['jobid'], name='jobid_idx'),
        ]
    
class Job_task(models.Model):
    job_id = models.ForeignKey(Job, verbose_name="任务定义")
    task_def_id = models.ForeignKey(Task_Def, verbose_name="任务定义")
    exe_user = models.CharField(max_length=64, verbose_name="执行用户") # 在远程主机上执行脚本或任务，主机上的用户
    params = models.TextField(verbose_name="参数")
    iphosts = models.TextField(verbose_name="IP或主机名") # 在远程主机上执行脚本或任务，主机上的用户
    timeout = models.IntegerField(verbose_name="超时时间")
    fromip = models.CharField(max_length=16, verbose_name="任务状态")
    create_user = models.CharField(max_length=64, verbose_name="创建用户")
    create_dt = models.DateTimeField(verbose_name="创建时间")
    update_dt = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    note = models.TextField(verbose_name="备注")

class Task(models.Model):
    job = models.ForeignKey(Job_task, verbose_name="作业任务")
    params = models.TextField(verbose_name="参数")
    executor = models.CharField(max_length=16, verbose_name="解析器")
    exe_user = models.CharField(max_length=16, verbose_name="执行用户")
    iphost = models.TextField(verbose_name="IP或主机名") # 在远程主机上执行脚本或任务，主机上的用户
    create_dt = models.DateTimeField(verbose_name="创建时间")
    update_dt = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    task_status = models.SmallIntegerField(verbose_name="任务状态")   # 0：失败  1：成功  2：等待  3：执行中
    note = models.TextField(verbose_name="备注")

jobtask/backup/20170913/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


#from .control.TaskDef import add as taskadd
from .control.TaskDef import AddView as taskdef_add_view
from .control.TaskDef import ListView as taskdef_list_view
from .control.TaskDef import DetailView as taskdef_detail_view
from .control.TaskDef import ActionView as taskdef_action_view
from .control.Ajax import TaskStatus
from .control.Ajax import TaskType
from .control.Ajax import TaskPerm
from .control.Ajax import FileType

jobtask/views/Ajax.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.http import JsonResponse
from .. import forms
from ..import models
import re

from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def get_data_list(data):
    datalist = []
    for (val, desc) in data:
        datalist.append({"value": val, "key": desc})
    return datalist

@csrf_exempt
def TaskStatus(request):
    task_status_map = [("", "请选择..."), ("1", "停用"),("2", "启用")]
    data = {"dataset": get_data_list(task_status_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def TaskType(request):
    task_type_map = [("", "请选择..."), (1, "系统任务"),(2, "普通任务")]
    data = {"dataset": get_data_list(task_type_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def TaskPerm(request):
    task_perm_status_map = [("", "请选择..."), (1, "独享"),(2, "共享")]
    data = {"dataset": get_data_list(task_perm_status_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def FileType(request):
    file_type_map = [("", "请选择..."),  (1, "单独文件"),(2, "执行包")]
    data = {"dataset": get_data_list(file_type_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def FileLocation(request):
    file_loc_choice = [("", "请选择..."),  (1, "本地"),(2, "远程服务器")]
    data = {"dataset": get_data_list(file_loc_choice)}
    return JsonResponse(data, safe=True)


@csrf_exempt
def IpList(request):
    queryset = models.SaltMinion.objects.all()
    dataset = []
    #dataset.append({"key":"", "value":"请选择..."})
    for item in queryset:
        dataset.append({"key":item.ip, "value":item.ip})
    data = {"dataset": dataset}
    return JsonResponse(data, safe=True)

jobtask/views/SubTask.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.decorators.cache import cache_page
from django.core.urlresolvers import reverse_lazy
from django.template import loader, Context

from django.contrib.auth.decorators import login_required  
from django.views import View
from django.views import generic

from lib.base.sdate import sdate

from .. import forms
from ..import models
import re
from django.http import JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.utils import timezone

# Create your views here.

class DetailView(generic.View):
    http_method_names = ["get", "post"]
    
    def http_method_not_allowed(self, request, *args, **kwargs):
        return HttpResponse("Not Allow")
    
    def get(self, request, *args, **kwargs):
        oid = kwargs.get("pk", None)
        taskid = kwargs.get("taskid", None)
        tpl_name = "jobtask/jobsubtask/detail.html"
        context = locals()
        context["oid"] = oid
        context["taskid"] = taskid
        context["title"] = u"子任务执行详情"
        return render_to_response(tpl_name, context)
    
    def post(self, request, *args, **kwargs):
        try:
            oid = kwargs.get("pk", None)
            taskid = kwargs.get("taskid", None)
            tpl_name = "jobtask/subtask/ajax_detail.html"
            context = locals()
            obj = get_object_or_404(models.SubTask, id=oid)
            context["object"] = obj
            t = loader.get_template(tpl_name)
            data = {"html": t.render(context), "msg": "ok" if obj.task_status==1 else "nook"}
            return JsonResponse(data)
        except Exception:
            import traceback
            print traceback.format_exc()
            pass

class ListView(generic.ListView):
    model = models.Job_SubTask
    template_name = 'jobtask/jobsubtask/list.html'  
    context_object_name = 'dataset'  
    paginate_by = 5 #加上这句就自动开启了分页功能
    allow_empty_first_page = True
    
    class Meta:
        ordering = ['-id']

    def get_querystr_without_page(self):
        query_string_all =  self.request.META.get("QUERY_STRING")
        querystr_widthout_page = re.sub(r"page=\d+", "", query_string_all)
        if querystr_widthout_page.startswith("&") or querystr_widthout_page.endswith("&"):
            querystr_widthout_page = querystr_widthout_page.strip("&")
        return querystr_widthout_page
    
    def get_queryset(self):  
        #cid = self.kwargs.get('cid','')  
        #articles_list = models.Task_Def.objects.filter(category=cid).order_by('-view_times').defer('text')  
        #taskdef_list = models.Task_Def.objects.all()
        fieldmap = {
            "task_status": "task_status",
            "task_type": "task_type",
            "task_perm": "task_perm_status",
            "file_type": "file_type",
        }
        querydict = self.request.GET
        condition = {}
        for (k,vs) in dict(querydict).items():
            if k in fieldmap:
                new_k = fieldmap[k]
                if vs[0]: condition[new_k] = vs[0]
        
        dataset = self.model.objects.filter(**condition)
        return dataset  
  
    def get_context_data(self,**kwargs):  
        context  = super(ListView,self).get_context_data(**kwargs)
        context["title"] = u"作业子任务列表"
        context["querystr"] = self.get_querystr_without_page()
        getmap = self.request.GET
        for (k,vs) in dict(getmap).items():
            if k == "page": continue  #排除分页参数
            for v in vs: # 有相同的参数
                context[k] = v
        return context

jobtask/templates/jobtask/comm_job_def/detail.html
{% extends "base/base.html" %}
{% load static %}
{% load bootstrap %}

{% block title %}
{{ title }}
{% endblock %}

{% block body%}

<style>
div.content {
padding: 8px 0;
border: 1px dashed #000;
}
div.datatable-row {
min-height: 40px;
}
div.datatable-row2 {
min-height: 40px;
}
div.row-right-part, div.row-left-part  {
}
div.page{
padding: 0px 15px;
}

div.block {
padding: 8px;
margin: 4px 0;
}
div.header-menu{
	float: right;
}
.block-placeholder {
    border: 1px dotted black;
}
span.open-close {
padding: 2px;
cursor: pointer;
font-weight: bold;
font-size: 14px;
}
</style>

	<div class="contain-fluid">
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<div class="p-info-container">
			         <div class="alert alert-danger p-info" style="display: none">
			         </div>
				</div>
			</div>
			<div class="col-md-2"></div>
		</div>
		
		<div class="row">
				<div class="col-md-1"></div>
				<div class="col-md-10">
					<form class="form" action="{{ action }}" name="postform" method="post" enctype="multipart/form-data">
					    {% csrf_token %}
					    {{ form|bootstrap:4 }}
					</form>
				</div>
				<div class="col-md-1"></div>
		</div>
		
		<div class="row" style="margin-bottom: 12px">
				<div class="col-md-1"></div>
				<div class="col-md-5 row-left-part">
					<div>
							<div style="display: inline-table;">候选任务</div>
					</div>
					<div class="content">
						<div class="contanier-fluid">
							<div class="row">
								<div class="col-md-12">
									<div class="tasklist"></div>
								</div>
							</div>
						</div>
						
					</div>
				</div>
				<div class="col-md-5 row-right-part">
					作业任务编排
					<div class="content">
							<div class="container-fluid container-task">
							<div class="row datatable-row dest-task">
							
								{% if jobtask_config %}  
								    {%for rec in jobtask_config %} 
								    <div class="col-md-12">
											    <div class="block bg-info">
											    		<div class="block-header">
											    			任务: {{ rec.comm_task.func}}->{{rec.comm_task.task.func}}
											    			<div class="header-menu"><span class="open-close" taskid="{{ rec.comm_task.id }}">+</span></div>
											    		</div>
											            <div class="block-content" style="display:none">
												            <div class="detail-info" >
												            	<ul>
													            	<li>任务: {{ rec.comm_task.task.func}}</li>
														            <li>IP:{{ rec.comm_task.iphosts}}</li>
														            <li>参数: {{ rec.comm_task.params}}</li>
														            <li>执行用户: {{ rec.comm_task.exe_user}}</li>
														            <li>超时时间: {{ rec.comm_task.timeout}}</li>
														            <li>功能: {{ rec.comm_task.func}}</li>
														            <li>创建时间: {{ rec.comm_task.create_dt}}</li>
														            <li>备注: {{ rec.comm_task.note}}</li>
													            </ul>
												            </div>
											            </div>
											    </div>
								    </div>
								    {% endfor%}  
								{% else %}  
								{% endif %}  
							
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-1"></div>
		</div>
		
		<div class="row">
				<div class="col-md-7"></div>
				<div class="col-md-4" style="text-align: right">
					    <a class="btn btn-danger btn-delete" action="delete" href="#">Delete</a>
					    <a class="btn btn-success btn-update" action="update" href="#">Update</a>
				</div>
				<div class="col-md-1"></div>
		</div>
	</div>

{% endblock %}

{% block js_extend %}
	<script src="{% static '/jquery/plugins/jquery.form.min.js' %}"></script>
	<script src="{% static 'django/csrf.js' %}"></script>
	<script src="{% static 'jquery_util.js' %}"></script>
	<link href="{% static 'plugins/select2-4.0.3/dist/css/select2.min.css' %}" rel="stylesheet">
	<script src="{% static 'plugins/select2-4.0.3/dist/js/select2.min.js' %}"></script>
	
	<script src="{% static 'jquery/plugins/jquery.ui.min.js' %}"></script>
	
	<script>
	
		function load(url){
			var tasks = "";
			$("div.container-task").find(".open-close").each(function(){
				tasks += ""+$(this).attr("taskid")+"|";
			});
			if(tasks != ""){
				url = $.trim(url)+"?"+"tasks="+tasks;
				url = url.replace("&?","&").replace("??","?");
			}
			$.get(url, undefined , function(htmlContent){
				$("div.tasklist").hide().html(htmlContent).fadeIn(500);
				$("div.datatable-row").find("div.block-header span").each(function(){
				 var $span = $(this);
				 $span.unbind("click");
				 $span.bind("click", function(){
					var html = $span.html();
					if(html == "-") {$span.html("+");}
					if(html == "+") {$span.html("-");}
					var $block = $span.parents("div.block");
					$block.children("div.block-content").toggle();
				 });
				});
				$("div.datatable-row").sortable({
					connectWith: ".datatable-row",
					cursor: 'move',
					//delay: 200
					forcePlaceholderSize: true,
					handle: ".block-header",
				    cancel: ".header-menu,.open-close" ,
					//revert: 100,
					placeholder: "ui-state-highlight",
					receive: function(event,ui){
						if($(this).hasClass("dest-task")){
							//如果原任务列表为空，则刷新
							if($("div.src-task").find("div.block").length == 0){
								load($(".btn-reset:first").attr("data-url"));
							}
							return true;
						}
						if($(this).hasClass("src-task")){
							var pagesize = $("div.pageinfo:first").attr("pagesize");
							var cnt = $(this).find("div.block").length;
							//如果原来任务数目比分页大，则刷新
							if(cnt > pagesize){
								load($(".btn-reset:first").attr("data-url"));
							}
						}
	
					},
				});
				
				$("div.page-row").find("a").each(function(){
					if(typeof($(this).attr("data-url"))=="undefined") {return true;}
					$(this).unbind("click");
					$(this).on("click", function(){
						load($(this).attr("data-url"));
					});
				});
			  });
		}
		
		load("{% url 'jobtask:my-comm-taskdef-list-task'%}");
	

		$(".select2").select2();
		var options = {
				selector: "#id_iphosts",
				url: "{% url 'jobtask:comm-iplist' %}",
				disp_fd: "key",
				val_fd: "value",
				value: "{{ object.iphosts }}",
				is_multiable: true,
		};
		load_data_for_select(options);


	    $(".btn-update, .btn-clone, .btn-delete").click(function(){
	    	var action = $(this).attr("action");
	    	var flag = confirm("确定要执行" + action + "操作吗?");
	    	if(flag == false){return false;}
			var tasks = "";
			$("div.container-task").find(".open-close").each(function(){
				tasks += ""+$(this).attr("taskid")+"|";
			});
	    	var form = $("form[name=postform]");  
            var options  = {      
                    url: form.attr("action")+"?" + "_action=" + action,
                    type:'post',
                    data: {
                       	"job_status": $("select[name=job_status]").val(),
                       	"job_class": $("select[name=job_class]").val(),
                       	"func": $("textarea[name=func]").val(),
                       	"note": $("textarea[name=note]").val(),
                       	"tasks": tasks
                    },
                    success:function(data)      
                    {    //成功执行的方法 
                    	console.info(data);
                    	var ret_code = data["code"];
                    	var ret_errmsg = data["errmsg"];
                    	var ret_action = data["action"];
                    	var ret_list_url = data["list_url"];
                    	if (ret_code != 0){
                    		$("div.p-info").html(""+ret_errmsg).hide().show(10);
                    		return false;
                    	}
                    	if(ret_action=="delete"){window.location = ret_list_url;}
                    	if(ret_action=="update"){window.location.reload();}
                    }      
            };      
            form.ajaxSubmit(options);  
            return false; //防止刷新提交
	    });
	    
	</script>

{% endblock %}