helloworld/urls.py
# coding: utf-8
"""helloworld URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

from . import view
from testModel import views
from book.tv import qq
from book import views as book_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hello$', view.hello),
    url(r'^qq/$', qq.show ),
    #url(r'^display/$', book_views.display_meta ),
    url(r'^display/$', book_views.display_meta_by_tpl),
    url(r'^book/author_form/$', book_views.author_form),
    url(r"abcd/(\d+)/(\d+)/$", view.test_url, name="abc"),
    url(r"home/$", view.home, name="home"),
    url(r"^jobtask/", include("jobtask.urls", namespace="jobtask")),   # 使用include
]

jobtask/backup/20170913/urls.py
from django.conf.urls import url


from jobtask import views as jobtask_views

app_name = "jobtask"  # namespace
urlpatterns = [
    #url(r"taskdef/add$", jobtask_views.taskadd, name="taskdef-add"),
    url(r"taskdef/add$", jobtask_views.taskdef_add_view.as_view(), name="taskdef-add"),
    url(r'^taskdef/(?P<pk>\d+)$', jobtask_views.taskdef_detail_view.as_view(), name='taskdef-detail'),
    url(r'^taskdef/action$', jobtask_views.taskdef_action_view.as_view(), name='taskdef-action'),
    url(r"taskdef/list$", jobtask_views.taskdef_list_view.as_view(), name="taskdef-list"),
    # ajax
    url(r"taskdef/status$", jobtask_views.TaskStatus, name="taskdef-status"),
    url(r"taskdef/type$", jobtask_views.TaskType, name="taskdef-type"),
    url(r"taskdef/perm$", jobtask_views.TaskPerm, name="taskdef-perm"),
    url(r"taskdef/filetype$", jobtask_views.FileType, name="taskdef-filetype"),
]

jobtask/urls.py
#coding=utf-8
"""helloworld URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url


import views

app_name = "jobtask"  # namespace
urlpatterns = [
    ## TaskDef
    #url(r"taskdef/add$", jobtask_views.taskadd, name="taskdef-add"),
    url(r"taskdef/add$", views.TaskDef.AddView.as_view(), name="taskdef-add"),
    url(r'^taskdef/(?P<pk>\d+)$', views.TaskDef.DetailView.as_view(), name='taskdef-detail'), #old
    url(r"^taskdef/list$", views.TaskDef.ListView.as_view(), name="taskdef-list"),
    # ajax
    url(r"^taskdef/status$", views.Ajax.TaskStatus, name="taskdef-status"),
    url(r"^taskdef/type$", views.Ajax.TaskType, name="taskdef-type"),
    url(r"^taskdef/perm$", views.Ajax.TaskPerm, name="taskdef-perm"),
    url(r"^taskdef/filetype$", views.Ajax.FileType, name="taskdef-filetype"),
    url(r"^taskdef/fileloc$", views.Ajax.FileLocation, name="taskdef-filelocation"),
    url(r"^iplist$", views.Ajax.IpList, name="comm-iplist"),
    ## CommTaskDef
    url(r"^comm_taskdef/new$", views.CommTaskDef.AddView.as_view(), name="comm_taskdef-new"),
    url(r"^comm_taskdef/list$", views.CommTaskDef.ListView.as_view(), name="comm_taskdef-list"),
    url(r"^comm_taskdef/(?P<pk>\d+)$", views.CommTaskDef.DetailView.as_view(), name="comm_taskdef-detail"),
    url(r"^comm_taskdef/modal/(?P<pk>\d+)$", views.CommTaskDef.DetailViewForModal.as_view(), name="comm_taskdef-detail_for_modal"),
    ## CommJobDef
    url(r"^comm_jobdef/new$", views.CommJobDef.AddView.as_view(), name="comm_jobdef-new"),
    url(r"^comm_jobdef/list$", views.CommJobDef.ListView.as_view(), name="comm_jobdef-list"),
    url(r"^comm_jobdef/(?P<pk>\d+)$", views.CommJobDef.DetailView.as_view(), name="comm_jobdef-detail"),
    url(r"^comm_jobdef/modal/(?P<pk>\d+)$", views.CommJobDef.DetailViewForModal.as_view(), name="comm_jobdef-detail_for_modal"),

    ## Job
    url(r"^job/list$", views.Job.ListView.as_view(), name="job-list"),
    url(r"^job/(?P<pk>\d+)/(?P<jobid>\d+)$", views.Job.DetailView.as_view(), name="job-detail"),
    #url(r"^job/(?P<pk>\d+)$", views.Job.DetailView.as_view(), name="job-detail"),
    url(r"^job/run/(\d+)$", views.Job.RunJob.as_view(), name="job-new"),
    ## JobTask
    url(r"^jobtask/list$", views.JobTask.ListView.as_view(), name="jobtask-list"),
    url(r"^jobtask/(?P<pk>\d+)/(?P<jobid>\d+)/(?P<job_order_id>\d+)$", views.JobTask.DetailView.as_view(), name="jobtask-detail"),
    ## JobSubTask
    url(r"^jobsubtask/list$", views.JobSubTask.ListView.as_view(), name="jobsubtask-list"),
    url(r"^jobsubtask/(?P<pk>\d+)/(?P<taskid>\d+)$", views.JobSubTask.DetailView.as_view(), name="jobsubtask-detail"),
    ## Task
    url(r"^task/list$", views.Task.ListView.as_view(), name="task-list"),
    url(r"^task/(?P<pk>\d+)/(?P<taskid>\d+)$", views.Task.DetailView.as_view(), name="task-detail"),
    url(r"^task/commtask/run/(\d+)$", views.Task.Run.as_view(), name="comm-task-run"),
    url(r"^task/run/(\d+)$", views.Task.RunTask.as_view(), name="task-run"),
    ## SubTask
    url(r"^subtask/list$", views.SubTask.ListView.as_view(), name="subtask-list"),
    url(r"^subtask/(?P<pk>\d+)/(?P<taskid>\d+)$", views.SubTask.DetailView.as_view(), name="subtask-detail"),
]

## 用户
urlpatterns += [
    ## TaskDef
    url(r"task/def$", views.TaskDef.AddView.as_view(), name="create-my-taskdef"),
    url(r"^task/def/my$", views.TaskDef.ListView.as_view(), {"user-open": True}, name="my-taskdef-list"),
    #url(r'^task/def/my/(?P<pk>\d+)$', views.TaskDef.DetailView.as_view(), name='my-taskdef-detail'), #old
    url(r"^comm_taskdef/list/my$", views.CommTaskDef.ListView.as_view(), {"user-open": True}, name="my-comm-taskdef-list"),
    url(r"^comm_taskdef/listtask/my$", views.CommTaskDef.ListTask.as_view(), {"user-open": True}, name="my-comm-taskdef-list-task"),
    url(r"^comm_jobdef/list/my$", views.CommJobDef.ListView.as_view(), {"user-open": True}, name="my-comm-jobdef-list"),
    url(r"^job/list/my$", views.Job.ListView.as_view(), {"user-open": True}, name="my-job-list"),
    url(r"^jobtask/list/my$", views.JobTask.ListView.as_view(), {"user-open": True}, name="my-jobtask-list"),
    url(r"^task/list/my$", views.Task.ListView.as_view(), {"user-open": True}, name="my-task-list"),
]

jobtask/forms/JobForm.py
# coding: utf8
'''
Created on 2017年8月26日

@author: qiueer
'''

from django import forms
from django.utils.translation import ugettext_lazy as _

from ..models import Job

class JobForm(forms.ModelForm):
    
    class Meta(object):  ## 通用视图CreateView需要使用到
        model = Job
        fields = "__all__"  # 效果与下列的相同
        #fields = ("file", "file_type", "main_script_name", "params", "executor", "task_status", "task_type", "task_perm_status", "func", "create_dt", "update_dt", "create_user")
        #exclude = ['create_dt', "update_dt", "create_user"]
        exclude = ['create_dt', "update_dt", "create_user"]  ## 这两个字段在model中设置为auto_now_add和auto_now，是不可改变的，所以要排除掉

jobtask/forms/Task.py
# coding: utf8
'''
Created on 2017年8月26日

@author: qiueer
'''

from django import forms
from django.utils.translation import ugettext_lazy as _

from ..models import Task

class RunTaskForm(forms.ModelForm):
    class Meta(object):  ## 通用视图CreateView需要使用到
        model = Task
        fields = ("params", "exe_user", "timeout", "iphosts", "note")
    
        widgets = {
            "params": forms.Textarea(
                attrs={"rows": 1}),
            "note": forms.Textarea(
                attrs={"rows": 2}),
            "timeout": forms.NumberInput(),
            'exe_user': forms.Select(
                attrs={'class': 'select2',
                       'data-placeholder': _('Select task def')}),
            'iphosts': forms.SelectMultiple(
                attrs={'class': 'select2',
                       'data-placeholder': _('Select task type')}),
        }
    

jobtask/forms/conf.py
typemap = [
    (1, "后台自动处理"),   # 前端不用配置
    (2, "普通"),  # 前端配置
]

jobtask/backup/20170913/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


#from .control.TaskDef import add as taskadd
from .control.TaskDef import AddView as taskdef_add_view
from .control.TaskDef import ListView as taskdef_list_view
from .control.TaskDef import DetailView as taskdef_detail_view
from .control.TaskDef import ActionView as taskdef_action_view
from .control.Ajax import TaskStatus
from .control.Ajax import TaskType
from .control.Ajax import TaskPerm
from .control.Ajax import FileType

jobtask/views/Ajax.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.http import JsonResponse
from .. import forms
from ..import models
import re

from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def get_data_list(data):
    datalist = []
    for (val, desc) in data:
        datalist.append({"value": val, "key": desc})
    return datalist

@csrf_exempt
def TaskStatus(request):
    task_status_map = [("", "请选择..."), ("1", "停用"),("2", "启用")]
    data = {"dataset": get_data_list(task_status_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def TaskType(request):
    task_type_map = [("", "请选择..."), (1, "系统任务"),(2, "普通任务")]
    data = {"dataset": get_data_list(task_type_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def TaskPerm(request):
    task_perm_status_map = [("", "请选择..."), (1, "独享"),(2, "共享")]
    data = {"dataset": get_data_list(task_perm_status_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def FileType(request):
    file_type_map = [("", "请选择..."),  (1, "单独文件"),(2, "执行包")]
    data = {"dataset": get_data_list(file_type_map)}
    return JsonResponse(data, safe=True)

@csrf_exempt
def FileLocation(request):
    file_loc_choice = [("", "请选择..."),  (1, "本地"),(2, "远程服务器")]
    data = {"dataset": get_data_list(file_loc_choice)}
    return JsonResponse(data, safe=True)


@csrf_exempt
def IpList(request):
    queryset = models.SaltMinion.objects.all()
    dataset = []
    #dataset.append({"key":"", "value":"请选择..."})
    for item in queryset:
        dataset.append({"key":item.ip, "value":item.ip})
    data = {"dataset": dataset}
    return JsonResponse(data, safe=True)

jobtask/views/CommJobDef.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.decorators.cache import cache_page
from django.core.urlresolvers import reverse_lazy

from django.contrib.auth.decorators import login_required  
from django.views import View
from django.views import generic
from django.shortcuts import get_object_or_404, render_to_response

from django.http import JsonResponse
from django.http import HttpResponse

from lib.base.sdate import sdate
from .QBase import QBaseDetailView
from .QBase import QBaseCreateView

from .. import forms
from .. import models
import re
from jobtask.views import CommTaskDef
from jobtask.views.CommJobDef2 import DetailView

# Create your views here.

class AddView(QBaseCreateView):
    model = models.Comm_Job_Def  ## 必填
    form_class  =   forms.CommJobDefFormNew## 必填
    template_name = "jobtask/comm_job_def/new.html"  ## 必填
    title = u"创建新作业"
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        now  = sdate().datetime_human()
        update_or_add_fds = {
            "create_dt": now,
            "update_dt": now,
            "create_user": self.request.user.username or 'Admin',
        }
        for (k, v) in update_or_add_fds.iteritems():
            setattr(obj, k, v)
        #obj.iphosts = ";".join(self.request.POST.getlist("iphosts",[]))
        #return super(QBaseCreateView, self).form_valid(form)
        #print self.request.POST.getlist("comm_tasks")
        
        obj.save()
        #comm_tasks = form.cleaned_data["comm_tasks"]
        tasks = self.request.POST.get("tasks", None)
        if not tasks:
            return self.ret_err_msg("tasks", "任务", "任务不能为空")
        taskids = [int(tid) for tid in str(tasks).strip("|").split("|")]

        #print tasks, taskids
        for tid in taskids:
            ct = models.Comm_Task_Def.objects.get(id=tid)
            models.CommJobTaskConfig.objects.create(comm_job_id=obj.id, comm_task_id=ct.id)
            #obj.comm_tasks.add(ct)
        return QBaseCreateView.form_valid(self, form)
    
##用于更新、删除，继承于UpdateView
class DetailView(QBaseDetailView):
    model = models.Comm_Job_Def
    template_name = "jobtask/comm_job_def/detail.html" 
    list_url = reverse_lazy("jobtask:comm_jobdef-list") ## 必填
    form_class  =  forms.CommJobDefFormNew  ## 必填
    title = u"作业定义详情"
    
    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        jt_config = models.CommJobTaskConfig.objects.filter(comm_job_id=pk)
        context["jobtask_config"] = jt_config
        return context
    
    ## form校验通过，修改前更新
    def form_valid(self, form):
        obj = form.save(commit=False)
        now  = sdate().datetime_human()
        update_or_add_fds = {
            "update_dt": now,
        }
        for (k, v) in update_or_add_fds.iteritems():
            setattr(obj, k, v)
        obj.save()
        
        tasks = self.request.POST.get("tasks", None)
        if not tasks:
            return self.ret_err_msg("tasks", "任务", "任务不能为空")
        taskids = [int(tid) for tid in str(tasks).strip("|").split("|")]

        models.CommJobTaskConfig.objects.filter(comm_job_id=obj.id).delete()
            
        for tid in taskids: ## 顺序新增
            ct = models.Comm_Task_Def.objects.get(id=tid)
            models.CommJobTaskConfig.objects.create(comm_job_id=obj.id, comm_task_id=ct.id)
            #obj.comm_tasks.add(ct)
        return QBaseDetailView.form_valid(self, form)

class ListView(generic.ListView):
    model = models.Comm_Job_Def
    template_name = 'jobtask/comm_job_def/list.html'  
    context_object_name = 'dataset'  
    paginate_by = 5 #加上这句就自动开启了分页功能
    allow_empty_first_page = True
    
    class Meta:
        ordering = ['-id']

    def get_querystr_without_page(self):
        query_string_all =  self.request.META.get("QUERY_STRING")
        querystr_widthout_page = re.sub(r"page=\d+", "", query_string_all)
        if querystr_widthout_page.startswith("&") or querystr_widthout_page.endswith("&"):
            querystr_widthout_page = querystr_widthout_page.strip("&")
        return querystr_widthout_page
    
    def get_queryset(self):  
        #cid = self.kwargs.get('cid','')  
        #articles_list = models.Task_Def.objects.filter(category=cid).order_by('-view_times').defer('text')  
        #taskdef_list = models.Task_Def.objects.all()
        fieldmap = {
            "task_status": "task_status",
            "task_type": "task_type",
            "task_perm": "task_perm_status",
            "file_type": "file_type",
        }
        querydict = self.request.GET
        condition = {}
        for (k,vs) in dict(querydict).items():
            if k in fieldmap:
                new_k = fieldmap[k]
                if vs[0]: condition[new_k] = vs[0]

        ## 这里判断是否是个人的常规作业
        user_open = self.kwargs.get("user-open", False)
        if user_open == True:
            condition["create_user"] = self.request.user.username
        dataset = self.model.objects.filter(**condition).order_by("-id")
        return dataset  
  
    def get_context_data(self,**kwargs):  
        context  = super(ListView,self).get_context_data(**kwargs)
        context["title"] = u"作业列表"
        context["querystr"] = self.get_querystr_without_page()
        getmap = self.request.GET
        for (k,vs) in dict(getmap).items():
            if k == "page": continue  #排除分页参数
            for v in vs: # 有相同的参数
                context[k] = v
        return context

class DetailViewForModal(generic.DetailView):
    model = models.Comm_Job_Def
    template_name = "jobtask/modal/comm_jobdef_detail.html" 

jobtask/templates/jobtask/jobtask/list.html
{% extends "base/base.html" %}
{% load static %}

{% load pagetags %}

{% block title %}
{{ title }}
{% endblock %}


{% block body%}
    
<div class="container-fluid">

	<form action="" method="get">
	<div class="row query-row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
			<div class="container-fluid form">

				<div class="row"> <!-- row begin -->
					<div class="col-md-4">
						<div class="form-group">
			            	<label for="search" class="control-label required-field ">
			                	搜索
			            	</label>
							<input id="search" class="js-states form-control" value="{{ search }}" required name="search"  />
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
			            	<label for="btn_search" class="control-label required-field ">&nbsp;
			            	</label>
			            	<div class="">
			           	    	<input id="btn_search"  class="btn btn-success" type="submit" value="过滤" />
			            	</div>
							
						</div>
					</div>
				</div> <!-- row  end-->
			</div>
		</div>
		<div class="col-md-1"></div>
	</div>
	</form>
	
	<div class="row header-row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
			<div class="container-fluid" style="padding: 0px; margin: 0px;">
				<div class="row">
					<div class="col-md-4">
						<div class="datatable-desc">
							<span style="font-size: 18px; margin: 0 auto; vertical-align: middle; display:inline-block">作业-任务信息表</span>
						</div>
					</div>
					<div class="col-md-6"></div>
					<div class="col-md-2">
					</div>
				</div> <!-- row -->
				<hr />
			</div><!-- container -->
		</div>
		<div class="col-md-1"></div>
	</div>
	
	<div class="row datatable-row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
				{% if dataset %}  
				    <table class="table tablesorter-dropbox">  
				        <thead>  
				        	<th>ID</th>  
				            <th>作业号</th> 
				            <th>执行用户</th>  
				            <th>参数</th>  
				            <th>IP或主机(s)</th>  
				            <th>超时时间</th>  
				            <th>来源IP</th>
				            <th>创建用户</th> 
				            <th>创建时间</th>  
				            <th>作业任务状态</th>  
				        </thead>
				    {%for rec in dataset %}  
				        <tr class="tb_row">  
				            <td>
				            	<a href="{% url 'jobtask:jobtask-detail'  rec.id rec.job.id rec.job.jobid%}">{{ rec.id }}</a>
				            </td>
				            <td>
				            	<a href="{% url 'jobtask:job-detail'  rec.job.id rec.job.jobid %}">{{ rec.job.jobid }}</a>
				            </td>  
				            <td>{{ rec.exec_user}}</td> 
				            <td>{{ rec.params}}</td>  
				            <td>{{ rec.iphosts}}</td>  
				            <td>{{ rec.timeout}}</td> 
				            <td>{{ rec.fromip}}</td>  
				            <td>{{ rec.create_user}}</td>  
				            <td>{{ rec.create_dt}}</td>  
				            <td>{{ rec.job_task_status}}</td>  
				        </tr>  
				    {% endfor%}  
				    </table>  
				{% else %}  
				<p>No Data !!!</p>  
				{% endif %}  
		</div>
		<div class="col-md-1"></div>
	</div>
	
	<div class="row page-row" style="padding: 0px; margin: 0px;">
		<div class="col-md-1"></div>
		<div class="col-md-10"  style="padding: 0px; margin: 0px;">
				{% if is_paginated %}  
		        <div class="panel-default"  style="align: right">
	                <ul class="pagination">
	                    <li><a href="{{ request.path }}?page=1&{{ querystr }}">&laquo;</a></li>
	                    {% if page_obj.has_previous %}
	                        <li><a href="{{ request.path }}?&page={{ page_obj.previous_page_number }}&{{ querystr }}">上一页</a></li>
	                    {% else %}
	                        <li class="previous disabled"><a>上一页</a></li>
	                    {% endif %}
<!-- 	                    {% for i in page_obj.paginator.page_range %}
	                        <li {% if page_obj.number == i %}class="active"{% endif %}><a href="{{ request.path }}?page={{ i }}&{{ querystr }}">{{ i }}</a></li>
	                    {% endfor %} -->
	                    {% for i in page_obj|page_range:8 %}
	                        <li {% if page_obj.number == i %}class="active"{% endif %}><a href="{{ request.path }}?page={{ i }}&{{ querystr }}">{{ i }}</a></li>
	                    {% endfor %}
	                    {% if page_obj.has_next %}
	                        <li><a href="{{ request.path }}?page={{ page_obj.next_page_number }}&{{ querystr }}">下一页</a></li>
	                    {% else %}
	                        <li class="previous disabled"><a>下一页</a></li>
	                    {% endif %}
	                    <li><a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}&{{ querystr }}">&raquo;</a></li>
	                </ul>
	        </div>
			 {%endif%}  
		</div>
		<div class="col-md-1"></div>
	</div>
	

</div>


<div id="commtask_modal" class="modal fade  " tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel">任务详细信息</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
          	<div class="content"></div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="runjob" class="modal fade  " tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel">作业提示</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-12">
          	<div class="content">
          		作业已创建，可点击查看：<a href="" target="blank"></a>
          	</div>
          	<div class="errmsg"></div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block js_extend %}
	<script src="{% static 'jquery/plugins/tablesort/js/jquery.tablesorter.min.js' %}"></script>
	<script src="{% static 'jquery/plugins/jquery.ui.min.js' %}"></script>
	<link href="{% static 'plugins/select2-4.0.3/dist/css/select2.min.css' %}" rel="stylesheet">
	<script src="{% static 'plugins/select2-4.0.3/dist/js/select2.min.js' %}"></script>
	<script src="{% static 'util.js' %}"></script>
	<script src="{% static 'django/csrf.js' %}"></script>
	<script src="{% static 'jquery_util.js' %}"></script>
	<script>
	$(function(){

		$("#commtask_modal,#runjob").draggable({   
		    handle: ".modal-header",   
		    cursor: 'move',   
		    refreshPositions: false  
		});  
		
		$('#commtask_modal').on('show.bs.modal', function (event) {
			  var button = $(event.relatedTarget); // Button that triggered the modal
			  var cid = button.data('commtask'); // Extract info from data-* attributes
			  var url = button.data("url");
			  var modal = $(this);
			  $.get(url, undefined , function(htmlContent){
				  modal.find('.modal-body div.content').html(htmlContent);
				  //modal.modal('toggle');  // 触发弹出
				});
			  //modal.find('.modal-body input').val(recipient)
			});
			
		$('#runjob').on('show.bs.modal', function (event) {
			  var button = $(event.relatedTarget); // Button that triggered the modal
			  var url = button.data("url");
			  var modal = $(this);
			  $.post(url, undefined , function(jsonobj){
				  var jobid = jsonobj.jobid;
				  var msg = jsonobj.msg;
				  var code = jsonobj.code;
				  var url = jsonobj.url;
				  if(code==0){
				  	modal.find('.modal-body div.content a').text(jobid).show();
				  	modal.find('.modal-body div.content a').attr("href", url);
				  }else{
					modal.find('.modal-body div.content').hide();
					modal.find('.modal-body div.errmsg').html(msg);
				  }
				});
			});
		
		$('table').tablesorter({
			widgets        : ['zebra', 'columns'],
			usNumberFormat : false,
			sortReset      : true,
			sortRestart    : true
		});
		
	});
	</script>

{% endblock %}